In [3]:
# NumPy Array Indexing
# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.

# Access 1-D Arrays
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4


IndexError: index 4 is out of bounds for axis 0 with size 4

In [4]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [9]:
# Access 2-D Arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0,2])
print(arr[1,2])
print(arr[1,-2])
print(arr[0,-1])
print(arr[0,-3])

[[1 2 3]
 [4 5 6]]
3
6
5
3
1


In [43]:
# Access 4 Arrays
arr = np.array([[[[1,2,3],[4,5,6]],[[0,0,0],[0,0,0]],[[11,12,13],[14,15,16]]]])
print(arr.ndim)
print(arr)
print(arr[0,0,0,0])
print(arr[0,0,1,-1])
print(arr[0,2,1,-1])


4
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 0  0  0]
   [ 0  0  0]]

  [[11 12 13]
   [14 15 16]]]]
1
6
16
