In [1]:
# Slicing arrays
# Slicing in python means taking elements from one given index to another given index.
# We pass slice instead of index like this: [start:end-1].
# We can also define the step, like this: [start:end-1:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1

In [4]:
import numpy as np
# slicing with 1-D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [20]:
print(arr[1:3]) 
print(arr[1:-2])
print(arr[-1:-5])
print(arr[-5:-1])
print(arr[-1:-5:-1])
print(arr[-2:1:-1])

[2 3]
[2 3]
[]
[1 2 3 4]
[5 4 3 2]
[4 3]


In [32]:
# slicing with 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr[1,0:2+1])
print(arr[0,-1:-3-1:-1])

[[1 2 3]
 [4 5 6]]
2
[4 5 6]
[3 2 1]


In [49]:
# slicing with 3-D array
arr = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[0,0,0]]])
print("dimension of array : " , arr.ndim)
print(arr)
print(arr[0,0,0])
print(arr[1,0,0])
print(arr[1,0,0:2+1])
print(arr[1,1,0:2])

dimension of array :  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [ 0  0  0]]]
1
11
[11 12 13]
[0 0]
