In [ ]:
# Iterating Arrays
# Iterating means going through elements one by one.
# As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
# If we iterate on a 1-D array it will go through each element one by one.

In [3]:
import numpy as np
# 1-D array-
arr = np.array([1,2,3,4,5])
print(arr)
for i in arr:
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [10]:
# 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr, "->",arr.ndim)
for i in arr:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]] -> 2
1
2
3
4
5
6


In [15]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr,"->",arr.ndim)
for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] -> 3
1
2
3
4
5
6
7
8
9


In [ ]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
# It solves some basic issues which we face in iteration, lets go through it with examples.


In [22]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
# Iterating Array With Different Data Types
# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
# NumPy does not change the data type of the element in-place (where the element is in array) 
# so it needs some other space to perform this action,
# that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].



In [23]:

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [25]:
import numpy as np

arr = np.array([11, 0, -1])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=[bool],casting='unsafe'):
    print(x)


True
False
True


In [62]:
# Iterating With Different Step Size

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],[1, 2, 3, 4],
                [11, 12, 17, 18]])

# arr[row_slice, col_slice]  ------ Slice rows and columns separately
print(arr[::,-1::-2])
print('\n')
print(arr[-1,-1::-2])
print('\n')
print(arr[::-1,-1::-2])


print('\n')

for x in np.nditer(arr[::2]):            # arr[row_slice] ----------------- Slice only rows, all columns included
  print(x)


[[ 4  2]
 [ 8  6]
 [ 4  2]
 [18 12]]


[18 12]


[[18 12]
 [ 4  2]
 [ 8  6]
 [ 4  2]]
-1


1
2
3
4
1
2
3
4


In [39]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.
# Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

(0,) 1
(1,) 2
(2,) 3


In [40]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [85]:
# Iterating With Different Step Size

arr = [[1, 2, 3, 4],
                [5, 6, 7, 8],[1, 2, 3, 4],
                [11, 12, 17, 18]]

for i in arr:
    print(i[-1::-2])
    
print('\n')


[4, 2]
[8, 6]
[4, 2]
[18, 12]




In [86]:

arr = [[1, 2, 3, 4],
                [5, 6, 7, 8],[1, 2, 3, 4],
                [11, 12, 17, 18]]

for i in arr:
    print(i[1::2])
    
print('\n')

[2, 4]
[6, 8]
[2, 4]
[12, 18]




In [2]:
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [11, 12, 17, 18]]

# Reverse the outer list
reversed_arr = arr[::-1]
print(reversed_arr)
# For each inner list, print elements starting from the last element, stepping backwards by 2
for sublist in reversed_arr:
    print(sublist[::-2])


[[11, 12, 17, 18], [1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]]
[18, 12]
[4, 2]
[8, 6]
[4, 2]
