In [ ]:
# Reshaping arrays:--------
# Reshaping means changing the shape (rows × columns) of an array without changing its data.
# Reshaping means changing the shape of an array.
# The shape of an array is the number of elements in each dimension.
# By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [1]:
import numpy as np

# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array (2x3):")
print(reshaped_arr)


Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


In [3]:
# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 3D array: 1 block, 2 rows, 3 columns
reshaped_arr = arr.reshape(1 ,2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array (2x3):")
print(reshaped_arr)


Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[[1 2 3]
  [4 5 6]]]


In [17]:
# 1st dimension = 1 (first block)
# 2nd dimension = 1 (second block inside first)
# 3rd dimension = 2 (rows)
# 4th dimension = 3 (columns)


# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])

# Reshape into 4D array: 1 block, 2 rows, 3 columns
reshaped_arr = arr.reshape(1, 1, 3, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array (2x3):")
print(reshaped_arr)


Original Array:
[1 2 3 4 5 6 7 8 9]

Reshaped Array (2x3):
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [27]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x= arr.reshape(2,4)
print(x,"shape of the array")
print(x.base,"base : array original array")
print(x.ndim,"dimension of x")
print("\n")
print(arr.reshape(2, 4).base)
print(arr.ndim)


[[1 2 3 4]
 [5 6 7 8]] shape of the array
[1 2 3 4 5 6 7 8] base : array original array
2 dimension of x


[1 2 3 4 5 6 7 8]
1
