In [ ]:
# Copy and View

# -----> 1. copy():
# copy() in NumPy creates a completely independent copy of the original array. 
# Changes made to the copy do not affect the original array.
# Example sentence:
# A copy creates a new array in memory, so its data is separate from the original array.

# -----> 2. view():
# view() in NumPy creates a new array object that looks at the same data as the original array.
# Changes made to the view affect the original array, and vice versa.
# Example sentence:
# A view shares the data buffer with the original array, so changes in one will reflect in the other.

In [2]:
# COPY: If I change the original array arr, it will not affect the copied array x.
# Similarly, if I change x, it will not affect the original array arr.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 42
x = arr.copy()
x[4] = 100

print(arr)
print(x)

[ 42   2   3   4 100]
[ 42   2   3   4 100]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 42
x = arr.copy()
arr[4] = 100

print(arr)
print(x)

[ 42   2   3   4 100]
[42  2  3  4  5]


In [27]:
arr = np.array([100,200,300,400,500,600,700])
print(arr)
print('\n')
copyy = arr.copy()
copyy[2] = 111111
print(copyy,"-> i affect in (copyy) for check this (affect in original array) or not")
print(arr,"-> this (not affected by copyy)")
print("\n")
arr[5] = 2222222
print(arr,"-> i affect in (original arr) for check this (affect in copyy) or not")
print(copyy,"-> this (not affected by array)")



[100 200 300 400 500 600 700]


[   100    200 111111    400    500    600    700] -> i affect in (copyy) for check this (affect in original array) or not
[100 200 300 400 500 600 700] -> this (not affected by copyy)


[    100     200     300     400     500 2222222     700] -> i affect in (original arr) for check this (affect in copyy) or not
[   100    200 111111    400    500    600    700] -> this (not affected by array)


In [22]:
# VIEW:
# If I change the original array arr, it will affect the view array y.
# Similarly, if I change y, it will affect the original array arr.

arr = np.array([1,2,3,4,5,6])
print(arr,"dimension of array is " , arr.ndim)
print("\n")
print(arr,"this is an original array")

viewy = arr.view()
print(viewy,"this is an view array")
print("\n")
viewy[2] = 100
print(viewy,"-> i affect in (viewy) for check this (affect in original array) or not")
print(arr,"-> yes this (affected by viewy)")
print("\n")
arr[5] = 00000
print(arr,"-> i affect in (original arr) for check this (affect in viewy) or not")
print(viewy,"-> yes this (affected by array)")



[1 2 3 4 5 6] dimension of array is  1


[1 2 3 4 5 6] this is an original array
[1 2 3 4 5 6] this is an view array


[  1   2 100   4   5   6] -> i affect in (viewy) for check this (affect in original array) or not
[  1   2 100   4   5   6] -> yes this (affected by viewy)


[  1   2 100   4   5   0] -> i affect in (original arr) for check this (affect in viewy) or not
[  1   2 100   4   5   0] -> yes this (affected by array)


In [ ]:
# now,copy has a owns data
# but view has not owns data ---------> but how can we check this?

# check :---
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.

In [28]:

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
