In [ ]:
# data distribution
# Data Distribution is a list of all possible values, and how often each value occurs.
# Such lists are important when working with statistics and data science.

In [ ]:
# Random distribution : probability function
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.1
# The probability for the value to be 5 is set to be 0.3
# The probability for the value to be 7 is set to be 0.6
# The probability for the value to be 9 is set to be 0
# the sum of all probabaility numbers should be one

In [4]:
import numpy as np
from numpy import random
arra = random.choice([3,4,-1,6],p=[0.1, 0.3, 0.6, 0.0],size=(10))
print(arra)
# in this example -1 probabaility is higher than other

[ 4  4 -1  4 -1 -1 -1 -1 -1  4]


In [5]:
# return 2-D with 3 rows and each containing 5 values:
arra = random.choice([3,4,-1,6],p=[0.1, 0.3, 0.6, 0.0],size=(3,5))
print(arra)

[[-1 -1  4  3 -1]
 [ 4 -1 -1  4 -1]
 [-1  4 -1 -1  4]]
