In [ ]:
# NumPy Searching Arrays
# Searching Arrays
# You can search an array for a certain value, and return the indexes that get a match.
# To search an array, use the where() method.

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,5,6,7,8,5])
print(arr)
x = np.where(arr == 5)
print(x)

[1 2 3 4 5 5 6 7 8 5]
(array([4, 5, 9], dtype=int64),)


In [7]:
# find the even number from the list
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [8]:
# find the odd number from the list
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4], dtype=int64),)


In [ ]:
# Search Sorted
# There is a method called searchsorted() which performs a binary search in the array,
# and returns the index where the specified value would be inserted to maintain the search order.

# The searchsorted() method is assumed to be used on sorted arrays.

In [12]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
# Search From the Right Side
# By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [14]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
x2 = np.searchsorted(arr, 7, side='left')

print("from right side",x)
print("from left side" ,x2)

from right side 2
from left side 1


In [ ]:
# Multiple Values
# To search for more than one value, use an array with the specified values.

In [18]:
# Find the indexes where the values 22, 44, and 76 should be inserted:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [7 , 5, 1])

print(x)


[3 2 0]
