In [ ]:
# NumPy Splitting Array
# Splitting is reverse operation of Joining.
# Joining merges multiple arrays into one and Splitting breaks one array into multiple.
# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
# If the array has less elements than required, it will adjust from the end accordingly.

In [8]:
import numpy as np
# Split the array in 3 parts:
arr = np.array([10, 27, 35, 44, 55, 6,9,6,8])
newarr = np.array_split(arr, 3)
print(newarr)
 # The return value is a list containing three arrays.

[array([10, 27, 35]), array([44, 55,  6]), array([9, 6, 8])]


In [9]:
# Split the array in 4 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# We also have the method split() available but it will not adjust the elements when
# elements are less in source array for splitting like in example above, 
# array_split() worked properly but split() would fail.

In [10]:
# Split Into Arrays
# split as an array.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr[0])
print(newarr[1])
print(newarr[2]) 

[1 2 3]
[4 5 6]


IndexError: list index out of range

In [12]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])

[1 2]
[3 4]


In [ ]:
# Splitting 2-D Arrays

In [13]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)
# eturns three 2-D arrays.

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [20]:
# Split the 2-D array into three 2-D arrays.


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18],[0,0,0]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [ 0,  0,  0]])]


In [27]:
# using split
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18],[0,0,0],[1,1,1]])
newarr1 = np.split(arr, 2)
print(newarr1)

print("error:---array split does not result in an equal division")
# using split example 2
arr = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18],[0,0,0],[1,1,1]])
newarr1 = np.split(arr, 2)
print(newarr1)

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18],
       [ 0,  0,  0],
       [ 1,  1,  1]])]
error:---array split does not result in an equal division


ValueError: array split does not result in an equal division

In [30]:
# Split the 2-D array into three 2-D arrays along columns.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [31]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [32]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [34]:
 # hstack()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hstack(arr)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [ ]:
# Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

In [35]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vstack(arr)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [38]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr,2)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]
