In [ ]:
# NumPy Joining Array
# Joining means putting contents of two or more arrays in a single array.
# We pass a sequence of arrays that we want to join to the concatenate() function, 
# along with the axis. If axis is not explicitly passed, it is taken as 0.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[11,12,31],[141,15,16]])
print(arr ,"array one")
print("\n")
print(arr1,"array two")
print("\n")
concate = np.concatenate((arr,arr1),axis=1)
print(concate)

[[1 2 3]
 [4 5 6]] array one


[[ 11  12  31]
 [141  15  16]] array two


[[  1   2   3  11  12  31]
 [  4   5   6 141  15  16]]


In [13]:
# Joining Arrays Using Stack Functions
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
| Feature            | `np.stack`                            | `np.concatenate`                           |
| ------------------ | ------------------------------------- | ------------------------------------------ |
| **Purpose**        | Combines arrays **along a new axis**  | Combines arrays **along an existing axis** |
| **New axis**       | Yes, always adds a new dimension      | No, uses existing dimensions               |
| **Shape change**   | Dimension of array **increases by 1** | Dimension **stays the same**               |
| **Axis parameter** | `axis` → index of the **new axis**    | `axis` → axis along which to join          |


In [17]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

# NumPy provides a helper function: vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.