In [19]:
# sorting array
# sort() fucntion use in array sorting
# sort() function sort a specified array
import numpy as np
arr = np.array([5,3,7,-1,0])
print(np.sort(arr)) # this is method is like the copy not affect in original array

[-1  0  3  5  7]


In [20]:
# sort the array alphabetically
arr = np.array(['u','o','a',])
print(np.sort(arr))


arr2 = np.array(['man','woman','yes','no'])
print(np.sort(arr2))

['a' 'o' 'u']
['man' 'no' 'woman' 'yes']


In [21]:
arr = np.array([True,False,False,True])
print(np.sort(arr))

[False False  True  True]


In [22]:
# sorting the 2 D array
arr = np.array([[3,2,1],[7,4,6]])
print(np.sort(arr))

[[1 2 3]
 [4 6 7]]


In [23]:
# sorting the 2 D array
arr = np.array([[[0,-1,4],[7,3,8]]])
print("dim->",arr.ndim,np.sort(arr))

dim-> 3 [[[-1  0  4]
  [ 3  7  8]]]


In [24]:
arr1 = np.array([1,2,3,-1,0,67])
arr2 = np.array([7,8,9])
con = np.concatenate((arr1,arr2))
print("before sorting : ", con)
print("after sorting : ",np.sort(con))

before sorting :  [ 1  2  3 -1  0 67  7  8  9]
after sorting :  [-1  0  1  2  3  7  8  9 67]
