In [ ]:
random number in numpy :
    Random number does NOT mean a different number every time.
    Random means something that can not be predicted logically.

In [13]:
import numpy as np
from numpy import random
# for int
randomnumber = random.randint(100)
print(randomnumber)

43


In [34]:
# for float : if you not provide number in the rand() its take value between 0 to 1.
randomnumber = random.rand()
print(randomnumber)

0.9268081086810063


In [40]:
# generate random Array
# generate a 1-D array containing 5 random list
arr = random.randint(100,size=(5))
print(arr)

[34 72 62 73 75]


In [46]:
# for int
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
arr = random.randint(100,size=(3,5))
print(arr)

# for float
# Generate a 2-D array with 3 rows, each row containing 5 random Float from 0 to 1
arr = random.rand(3,5)
print(arr)

[[84 44 10 92 88]
 [86 16 17 46 96]
 [74  4 11 20 24]]
[[0.62762924 0.77055503 0.12262646 0.07027431 0.79832416]
 [0.64969813 0.87813606 0.67189048 0.46125072 0.21180186]
 [0.06271433 0.43178858 0.89886915 0.27664109 0.92849359]]


In [64]:
# generate random number from an array using choice()
# The choice() method takes an array as a parameter and randomly returns one of the values.
# array pass in choice as a parameter
arr_picked = random.choice([8,4,5,6,7,0])
print(arr_picked)


8


In [70]:
# also we can diefind size : 
# generate random number from an 2-D array
arr_picked = random.choice([8,4,5,6,7,0],size=(3,5))
print(arr_picked)


[[8 6 0 8 4]
 [4 4 6 6 6]
 [7 8 4 8 8]]
