In [ ]:
# numpy sorting array
# Sorting means putting elements in an ordered sequence.
# Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
# The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [1]:
import numpy as np
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
# Note: This method returns a copy of the array, leaving the original array unchanged.

In [2]:
# Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [3]:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [4]:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [5]:

arr = np.array([[[3, 2, 4], [5, 0, 1],[0,-1,7]]])

print(np.sort(arr))

[[[ 2  3  4]
  [ 0  1  5]
  [-1  0  7]]]
